backend:
  name: git-gateway
  branch: master
  accept_roles:
    - admin
    - editor

site_url: https://academyparkpeds.netlify.com
display_url: https://academyparkpeds.netlify.com
# logo_url: https://your-site.com/images/logo.svg

show_preview_links: true

media_folder: "static/media"
public_folder: "/media"

collections:
  - name: "hero"
    label: "Hero"
    folder: "static/data/hero"
    delete: false
    create: true
    format: "json"
    preview_path: /
    fields:
      - {label: "Tagline", name: "tagline", widget: "string"}
      - label: "Site Alert"
        name: "alert"
        widget: "object"
        required: false
      - label: "News"
        name: "news"
        widget: "list"
        allow_add: true
        required: false
        fields:
          - {label: "Active", name: "active", widget: "boolean", default: true}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Text", name: "text", widget: "string", required: false}
          - {label: "Icon Class", name: "icon", widget: "string"}

