backend:
  name: git-gateway
  branch: master
  accept_roles:
    - admin
    - editor

site_url: https://academyparkpeds.netlify.com
display_url: https://academyparkpeds.netlify.com
# logo_url: https://your-site.com/images/logo.svg

show_preview_links: true

media_folder: 'static/_media'
public_folder: '/media'

collections:
  - name: 'settings'
    label: 'Settings'
    delete: false
    description: 'Update site alert & news items here.'
    editor:
      preview: false
    files:
      - name: 'alert'
        label: 'Site Alert'
        file: 'static/_data/alert.json'
        description: 'Popover Site Alert'
        fields: 
          - {label: 'Active', name: 'active', widget: 'boolean', default: true}
          - {label: 'Alert', name: 'title', widget: 'string'}
          - {label: 'Text', name: 'text', widget: 'markdown', required: false}
          - {label: 'Icon Class', name: 'icon', widget: 'string', hint: 'See here for available icons: https://fontawesome.com/icons?d=gallery&m=free'}
      - name: 'news'
        label: 'News Items'
        file: 'static/_data/news.json'
        fields:
          - label: 'News' 
            widget: 'list'
            name: 'news'
            allow_add: true
            required: false
            fields:
              - {label: 'Active', name: 'active', widget: 'boolean', default: true}
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Text', name: 'text', widget: 'string', required: false}
              - {label: 'Icon Class', name: 'icon', widget: 'string', hint: 'See here for available icons: https://fontawesome.com/icons?d=gallery&m=free'}
      - name: 'hours'
        label: 'Office Hours'
        file: 'static/_data/hours.json'
        fields:
          - label: 'Highlands Ranch Office Hours' 
            widget: 'list'
            name: 'hr_hours'
            allow_add: true
            required: true
            fields:
              - {label: 'Day', name: 'title', widget: 'select', options: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']}
              - {label: 'Open', name: 'open', widget: 'datetime', dateFormat: false, timeFormat: 'h mm a'}
              - {label: 'Close', name: 'close', widget: 'datetime', dateFormat: false, timeFormat: 'h mm a'}
          - label: 'Littleton Office Hours' 
            widget: 'list'
            name: 'lt_hours'
            allow_add: true
            required: true
            fields:
              - {label: 'Day', name: 'title', widget: 'select', options: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']}
              - {label: 'Open', name: 'open', widget: 'datetime', dateFormat: false, timeFormat: 'h mm a'}
              - {label: 'Close', name: 'close', widget: 'datetime', dateFormat: false, timeFormat: 'h mm a'}

